import type { Project } from "@/content/projects";

// English edition of content/projects.ts. The hackathon entries are translated
// line for line from HH_spam/Resume/Backend.tex.
export const projectsEn: Project[] = [
  {
    slug: "moscollector",
    title: "Accident forecasting service for Moscow utility tunnels",
    tier: 1,
    period: "September 2026",
    role: "Team captain, Backend",
    summary: "ML (Python, CatBoost) => DB => Backend (Java, Spring Boot) => Frontend (JS, Vue)",
    description: "Hackathon project.",
    bullets: [
      "Led a team of 5 (backend, ML, frontend): tasks in Jira, dailies and planning; deployed production with backups.",
      "Designed the architecture of data flows from external services (weather, hydrology, customer services) into ML and Frontend.",
    ],
    stack: ["Java", "Spring Boot", "Python", "CatBoost", "JavaScript", "Vue", "Jira"],
    categories: ["Backend", "ML"],
    links: [
      { label: "Hosting", href: "https://moscollector-goal.ru/" },
      { label: "Repositories", href: "https://github.com/hack-goal-team" },
    ],
  },
  {
    slug: "scanovich-webui",
    title: "MTS True Tech Hackathon",
    tier: 1,
    period: "2026",
    role: "Team project",
    summary: "Neural network orchestrator in Python integrated with a WebUI",
    description: "Developed a neural network orchestrator in Python and integrated it with a WebUI.",
    stack: ["Python", "WebUI"],
    categories: ["Backend", "ML"],
    links: [{ label: "GitHub", href: "https://github.com/FUYOH666/scanovich-webUI/" }],
  },
  {
    slug: "prassign",
    title: "PRAssign + AsyncFactorial",
    tier: 1,
    period: "November 2025 – January 2026",
    role: "Individual project",
    summary: "Go REST API + Scala/Kafka pipeline",
    description:
      "A Go service accepts tasks, Kafka hands them to Scala consumers for computation, and the state is stored in PostgreSQL.",
    stack: ["Scala", "Go", "Kafka", "Cats Effect 3", "PostgreSQL", "Nginx", "ScalaTest", "Docker", "k6"],
    categories: ["Backend", "DevOps"],
    links: [
      { label: "PRAssign", href: "https://github.com/UsatovPavel/PRAssign" },
      { label: "AsyncFactorial", href: "https://github.com/UsatovPavel/AsyncFactorial" },
    ],
  },
  {
    slug: "timetamer",
    title: "TimeTamer",
    tier: 1,
    featured: true,
    period: "February 2025 – August 2025",
    role: "Team project",
    summary: "Java server + Kotlin Android calendar app with AI and gamification",
    description:
      "Shared tasks, statistics, achievements, push notifications and authentication; client–server communication via Retrofit and WorkManager; a ChatGPT + Whisper AI assistant for task suggestions and voice input.",
    stack: ["Java", "Spring Boot", "Kotlin", "Jetpack Compose", "Retrofit", "WorkManager", "PostgreSQL", "Docker", "JUnit 4/5", "Mockito"],
    categories: ["Backend", "Android", "DevOps"],
    media: [
      {
        src: "/projects/timetamer/calendar-demo.mp4",
        poster: "/projects/timetamer/calendar-poster.jpg",
        title: "Smart Calendar",
        description: "Calendar, shared tasks and planning scenarios in the Android app.",
      },
      {
        src: "/projects/timetamer/ai-dialog-demo.mp4",
        poster: "/projects/timetamer/ai-dialog-poster.jpg",
        title: "AI dialog and voice input",
        description: "The ChatGPT assistant and Whisper speech recognition at work.",
      },
    ],
    links: [{ label: "GitHub", href: "https://github.com/hse-project-Java-2025" }],
  },
  {
    slug: "population-forecast",
    title: "ML population forecast",
    tier: 1,
    period: "individual project",
    role: "ML / time series",
    summary: "10-year time series forecasting",
    description:
      "Population forecasting over a 10-year horizon: comparing ARIMA, Prophet, XGBoost and Random Forest.",
    metric: "Best model, ARIMA with grid search: MAPE 0.020 on a held-out ten-year window.",
    stack: ["Python", "pandas", "scikit-learn", "XGBoost", "Prophet", "statsmodels", "SciPy"],
    categories: ["ML"],
    links: [{ label: "GitHub", href: "https://github.com/UsatovPavel/Pop_ML_Forecast10" }],
  },
  {
    slug: "voevoda",
    title: "Voevoda",
    tier: 1,
    period: "January 2024 – June 2024",
    role: "Team project",
    summary: "2D top-down RTS: command a general, capture cities, hire armies and fight the AI",
    description:
      "City and opponent generation, enemy behavior, AI army widgets, fog of war and battle mechanics.",
    stack: ["C++", "Unreal Engine 4"],
    categories: [],
    media: [
      {
        src: "/projects/voevoda/gameplay-demo.mp4",
        poster: "/projects/voevoda/gameplay-poster.jpg",
        title: "Voevoda gameplay",
        description: "Top-down RTS, combat mechanics and enemy behavior.",
      },
    ],
    links: [{ label: "GitHub", href: "https://github.com/UsatovPavel/Voevoda" }],
  },
  {
    slug: "ansible-deploy",
    title: "ansible-deploy + claude-web-console",
    tier: 1,
    period: "2026",
    role: "Individual project",
    summary: "Automated deployment of a web console for headless Claude Code on a VPS",
    description:
      "Tagged Ansible roles with secrets in ansible-vault for separate prod and test groups. Rootless systemd with ProtectSystem=strict, Certbot with a renewal hook, and SNI on Nginx.",
    stack: ["Ansible", "ansible-vault", "systemd", "Nginx", "Certbot", "Bash"],
    categories: ["DevOps"],
    links: [
      { label: "ansible-deploy", href: "https://github.com/UsatovAI/ansible-deploy" },
      { label: "claude-web-console", href: "https://github.com/UsatovAI/claude-web-console" },
    ],
  },
];

export const educationalProjectsEn: Project[] = [
  {
    slug: "java-git-cli",
    title: "Git CLI",
    tier: 2,
    period: "coursework",
    role: "Java",
    summary: "A CLI clone of Git",
    description: "The core operations of a version control system implemented as a console app.",
    stack: ["Java", "CLI"],
    categories: ["Backend"],
    links: [],
  },
  {
    slug: "zio-notification-service",
    title: "ZIO Notification Service",
    tier: 2,
    period: "coursework",
    role: "Scala",
    summary: "REST API for notifications",
    description: "A time-zone-aware notification service built on ZIO.",
    stack: ["Scala", "ZIO", "REST API"],
    categories: ["Backend"],
    links: [{ label: "GitHub", href: "https://github.com/UsatovPavel/ZIO-Notification-Service" }],
  },
  {
    slug: "antlr-parser",
    title: "ANTLR parser",
    tier: 2,
    period: "coursework",
    role: "Python",
    summary: "Regular expression parser",
    description: "A parser for the formal language of regular expressions, built with ANTLR.",
    stack: ["Python", "ANTLR"],
    categories: [],
    links: [{ label: "GitHub", href: "https://github.com/UsatovPavel/Usatov-FL-HSE/tree/task4-dev" }],
  },
  {
    slug: "portfolio-site",
    title: "This website",
    tier: 2,
    period: "July 2026 – August 2026",
    role: "TypeScript",
    summary: "My own portfolio site: Next.js + Tailwind",
    description:
      "Static export with five content variants (full/JVM/backend/ML/DevOps); deployed to a VPS with Nginx and Certbot.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Nginx"],
    categories: ["Backend"],
    links: [{ label: "GitHub", href: "https://github.com/UsatovAI/portfolio-site" }],
  },
];
